### ISSUE TITLE
serde chokes on binary deserialization

### ISSUE THREAD

**Issue by SuperFluffy** [bluss/rust-ndarray#240]
# Problem description

Serde chokes on deserialization of `ndarray::Array` when deserializing from binary. This might extend to non-json formats as well: I have been trying to serialize and deserialize an `Array2<f64>` with both `bincode` and `rmp` (`msgpack`), and in both cases errors are thrown.

The two code blocks at the bottom of the page are the versions for `rmp` and `bincode`, respectively. The error for `rmp` is as follows:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TypeMismatch(Array32)', ../src/libcore/result.rs:837
```

While the error for `bincode` is:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Serde(Custom("Invalid type. Expected `Seq`"))', ../src/libcore/result.rs:837
```

Deserializing the buffer written to a file in the `rmp` example Python yields the following:

```python
In [1]: import msgpack

In [2]: f = open('./test.txt', 'rb')

In [3]: msgpack.unpackb(f.read())
Out[3]: 
[1,
 [4, 4],
 [1.0,
  2.0,
  3.0,
  4.0,
  5.0,
  6.0,
  7.0,
  8.0,
  9.0,
  10.0,
  11.0,
  12.0,
  13.0,
  14.0,
  15.0,
  16.0]]
```

# Error hypothesis

Given the result of the Python deserialization, I believe the serialization itself to be working ok.

I suspect, but need to verify, that maybe the order of serialization and deserialization is not the same.

# Code examples to reproduce the error

## `rmp` version

+ `serde 0.8`
+ `ndarray 0.6.9`
+ `rmp_serde 0.10`

```rust
#![feature(proc_macro)]

extern crate ndarray;
extern crate rmp_serde;
extern crate serde;

#[macro_use]
extern crate serde_derive;

use serde::{Deserialize,Serialize};
use rmp_serde::Serializer;
use std::env;
use std::fs::File;
use std::io::{Cursor,SeekFrom};
use std::io::prelude::*;

fn main() {
    let a: ndarray::Array2<_> = ndarray::Array::linspace(1.0, 16.0, 16).into_shape((4,4)).unwrap();

    println!("{:?}", a);

    let mut bufcursor = Cursor::new(Vec::new());

    Serialize::serialize(&a, &mut Serializer::new(&mut bufcursor)).ok().unwrap();

    bufcursor.seek(SeekFrom::Start(0));

    let mut f = File::create("test.txt").unwrap();
    f.write(bufcursor.get_ref());

    bufcursor.seek(SeekFrom::Start(0));

    let mut deserializer = rmp_serde::Deserializer::new(bufcursor);
    let a_de: ndarray::Array2<f64> = Deserialize::deserialize(&mut deserializer).unwrap();

    println!("{:?}", a_de);
}
```

## `bincode` version

+ `ndarray: 0.6.9`
+ `serde: 0.8`
+ `bincode: 0.6`

```rust
#![feature(proc_macro)]

extern crate bincode;
extern crate ndarray;
extern crate serde;

#[macro_use]
extern crate serde_derive;

use bincode::SizeLimit::Infinite;
use serde::{Deserialize,Serialize};
use std::fs::File;
use std::io::BufWriter;
use std::io::prelude::*;

fn main() {
    let a: ndarray::Array2<_> = ndarray::Array::linspace(1.0, 16.0, 16).into_shape((4,4)).unwrap();

    println!("{:?}", a);

    let mut buf = bincode::serde::serialize(&a, Infinite).unwrap();

    let a_de: ndarray::Array2<f64> = bincode::serde::deserialize(&buf).unwrap();

    println!("{:?}", a_de);
}
```

**Comment by bluss** [comment]
This is documented in https://serde.rs/impl-deserialize.html under "two different styles of deserialization"

**Comment by bluss** [comment]
rustc-serialize + bincode works fine in a simple test

```rust
extern crate bincode;
extern crate ndarray;
extern crate rustc_serialize;

use bincode::SizeLimit::Infinite;
use std::fs::File;
use std::io::BufWriter;
use std::io::prelude::*;
use ndarray::{Array1, Array2};

fn main() {
    let a = Array1::linspace(1.0, 16.0, 16).into_shape((4,4)).unwrap();

    println!("{:?}", a);

    let mut buf = bincode::rustc_serialize::encode(&a, Infinite).unwrap();

    println!("buf={:?}", buf);

    let a_de: ndarray::Array2<f64> = bincode::rustc_serialize::decode(&buf).unwrap();

    println!("{:?}", a_de);
}
```

**Comment by SuperFluffy** [comment]
# Actual

The actual problem was that we did not implement `visit_seq` for the `ArrayVisitor`, which is needed when deserializing formats which are not self-describing, see https://serde.rs/deserialize-struct.html
